name = "proofs"
defaultTargets = ["A361032", "WOWII19", "A054390", "A001481", "A216971", "A337945", "A348840", "A326250", "A104896"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.34.1"

[[lean_lib]]
name = "A361032"
srcDir = "A361032"

[[lean_lib]]
name = "WOWII19"
srcDir = "WOWII19"

[[lean_lib]]
name = "A054390"
srcDir = "A054390"

[[lean_lib]]
name = "A001481"
srcDir = "A001481"

[[lean_lib]]
name = "A216971"
srcDir = "A216971"

[[lean_lib]]
name = "A337945"
srcDir = "A337945"

[[lean_lib]]
name = "A348840"
srcDir = "A348840"

[[lean_lib]]
name = "A326250"
srcDir = "A326250"

[[lean_lib]]
name = "A104896"
srcDir = "A104896"
