name = "proofs"
defaultTargets = ["A397588", "A389540", "A361032", "WOWII19", "A374571"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.34.1"

[[lean_lib]]
name = "A397588"
srcDir = "A397588"

[[lean_lib]]
name = "A389540"
srcDir = "A389540"

[[lean_lib]]
name = "A361032"
srcDir = "A361032"

[[lean_lib]]
name = "WOWII19"
srcDir = "WOWII19"

[[lean_lib]]
name = "A374571"
srcDir = "A374571"
